const USER_SIGNIN = "USER_SIGNIN";
const USER_REGISTRATION_TYPE = "USER_REGISTRATION_TYPE";
const USER_LOGIN_TYPE = "USER_LOGIN_TYPE";

export { USER_SIGNIN, USER_REGISTRATION_TYPE, USER_LOGIN_TYPE };
